spring.application.name=traductor
management.endpoints.web.exposure.include=health
management.endpoints.web.cors.allowed-origins=http://localhost:5173
management.endpoints.web.cors.allowed-methods=GET,POST,OPTIONS
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
